#!/usr/bin/env node
/**
 * Postinstall script to automatically generate wsx.d.ts in user's project
 *
 * This script runs after @wsxjs/wsx-core is installed and:
 * 1. Detects project structure (src/ directory or root)
 * 2. Creates wsx.d.ts in the appropriate location
 * 3. Ensures tsconfig.json includes the file
 */

import { existsSync, mkdirSync, writeFileSync, readFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Get the project root (where node_modules is located)
// This script runs from node_modules/@wsxjs/wsx-core/scripts/postinstall.mjs
// Strategy: Go up from scripts/ until we find node_modules, then go up one more level
function findProjectRoot() {
    let currentDir = __dirname;

    // Go up from scripts/ to find node_modules
    while (currentDir !== "/") {
        const parentDir = dirname(currentDir);
        const dirName = currentDir.split(/[/\\]/).pop();

        // If we're in node_modules, the project root is one level up
        if (dirName === "node_modules") {
            return parentDir;
        }

        // Check if parent is node_modules
        const parentDirName = parentDir.split(/[/\\]/).pop();
        if (parentDirName === "node_modules") {
            return parentDir;
        }

        currentDir = parentDir;
    }

    // Fallback: use process.cwd() (current working directory)
    // This should be the project root when npm/pnpm install runs
    try {
        const cwd = process.cwd();
        if (existsSync(join(cwd, "package.json"))) {
            return cwd;
        }
    } catch {
        // Ignore
    }

    // Last resort: assume we're in node_modules/@wsxjs/wsx-core/scripts
    // Go up 3 levels: scripts -> core -> node_modules -> project root
    return dirname(dirname(dirname(__dirname)));
}

// Determine where to place wsx.d.ts
function determineWsxTypesLocation(projectRoot) {
    const srcDir = join(projectRoot, "src");
    const typesDir = join(projectRoot, "types");

    // Priority 1: src/types/wsx.d.ts (most common)
    if (existsSync(srcDir)) {
        return {
            path: join(srcDir, "types", "wsx.d.ts"),
            dir: join(srcDir, "types"),
            location: "src/types/wsx.d.ts",
        };
    }

    // Priority 2: types/wsx.d.ts (root types directory)
    if (existsSync(typesDir)) {
        return {
            path: join(typesDir, "wsx.d.ts"),
            dir: typesDir,
            location: "types/wsx.d.ts",
        };
    }

    // Priority 3: src/wsx.d.ts (if src exists but no types subdir)
    if (existsSync(srcDir)) {
        return {
            path: join(srcDir, "wsx.d.ts"),
            dir: srcDir,
            location: "src/wsx.d.ts",
        };
    }

    // Priority 4: root wsx.d.ts (last resort)
    return {
        path: join(projectRoot, "wsx.d.ts"),
        dir: projectRoot,
        location: "wsx.d.ts",
    };
}

// Generate wsx.d.ts content
function generateWsxTypesContent() {
    return `// Type declaration for .wsx files
// This file is automatically generated by @wsxjs/wsx-core
// Generated at: ${new Date().toISOString()}
//
// You can safely:
// - Delete this file if you don't use .wsx files
// - Customize it as needed for your project
// - It will be regenerated on next install if deleted
//
// Location: This file is tracked by @wsxjs/wsx-core postinstall script
// To disable auto-generation, add this to your package.json:
//   "wsx": { "skipAutoTypes": true }

declare module "*.wsx" {
    import { WebComponent, LightComponent } from "@wsxjs/wsx-core";
    // Allow any class that extends WebComponent or LightComponent
    const Component: new (...args: unknown[]) => WebComponent | LightComponent;
    export default Component;
}
`;
}

// Update tsconfig.json to include the wsx.d.ts file
function updateTsConfig(projectRoot, wsxTypesLocation) {
    const tsconfigPath = join(projectRoot, "tsconfig.json");

    if (!existsSync(tsconfigPath)) {
        // No tsconfig.json - that's okay, user might not be using TypeScript yet
        return false;
    }

    try {
        const tsconfigContent = readFileSync(tsconfigPath, "utf-8");
        const tsconfig = JSON.parse(tsconfigContent);

        // Check if the file is already included
        const include = tsconfig.include || [];
        const alreadyIncluded = include.some((pattern) => {
            // Check if pattern matches the wsx.d.ts location
            if (pattern === wsxTypesLocation || pattern.includes(wsxTypesLocation)) {
                return true;
            }
            // Check common patterns
            if (pattern === "src/**/*" && wsxTypesLocation.startsWith("src/")) {
                return true;
            }
            if (pattern === "**/*" || pattern === "**/*.ts" || pattern === "**/*.d.ts") {
                return true;
            }
            return false;
        });

        if (alreadyIncluded) {
            return true; // Already included, no need to update
        }

        // Add the file to include array
        if (!tsconfig.include) {
            tsconfig.include = [];
        }

        // Add specific file or pattern
        if (!tsconfig.include.includes(wsxTypesLocation)) {
            tsconfig.include.push(wsxTypesLocation);
        }

        // Write back
        writeFileSync(tsconfigPath, JSON.stringify(tsconfig, null, 2) + "\n", "utf-8");
        return true;
    } catch (error) {
        // If tsconfig.json is invalid or we can't parse it, skip
        console.warn("[@wsxjs/wsx-core] Warning: Could not update tsconfig.json:", error.message);
        return false;
    }
}

// Main function
function main() {
    try {
        const projectRoot = findProjectRoot();

        // Check if this is actually a user project (not our own monorepo)
        const packageJsonPath = join(projectRoot, "package.json");
        if (!existsSync(packageJsonPath)) {
            // Not a valid project, skip
            return;
        }

        const pkg = JSON.parse(readFileSync(packageJsonPath, "utf-8"));

        // Check if user has disabled auto-generation
        if (pkg.wsx && pkg.wsx.skipAutoTypes === true) {
            return;
        }

        // Skip if this is our own monorepo
        // Check for monorepo indicators: pnpm-workspace.yaml, packages/ directory, or known wsxjs repo structure
        const isMonorepo =
            existsSync(join(projectRoot, "pnpm-workspace.yaml")) ||
            existsSync(join(projectRoot, "packages")) ||
            projectRoot.includes("wsxjs/packages") ||
            projectRoot.includes("wsxjs\\packages");

        if (isMonorepo || pkg.name === "@wsxjs/wsx-core") {
            return;
        }

        // Determine where to place wsx.d.ts
        const {
            path: wsxTypesPath,
            dir: wsxTypesDir,
            location: wsxTypesLocation,
        } = determineWsxTypesLocation(projectRoot);

        // Check if file already exists
        if (existsSync(wsxTypesPath)) {
            // File exists - check if it's our auto-generated one
            const existingContent = readFileSync(wsxTypesPath, "utf-8");
            if (existingContent.includes("@wsxjs/wsx-core")) {
                // It's our file, update it
                writeFileSync(wsxTypesPath, generateWsxTypesContent(), "utf-8");
                console.log(
                    `\n[@wsxjs/wsx-core] ✅ Updated wsx.d.ts at: ${wsxTypesLocation}\n   Full path: ${wsxTypesPath}\n`
                );
            } else {
                // User has custom wsx.d.ts, don't overwrite
                console.log(
                    `\n[@wsxjs/wsx-core] ℹ️  Found custom wsx.d.ts at: ${wsxTypesLocation}\n   Skipping auto-generation (file will not be overwritten)\n`
                );
                return;
            }
        } else {
            // Create directory if needed
            if (!existsSync(wsxTypesDir)) {
                mkdirSync(wsxTypesDir, { recursive: true });
            }

            // Create the file
            writeFileSync(wsxTypesPath, generateWsxTypesContent(), "utf-8");
            console.log(
                `\n[@wsxjs/wsx-core] ✅ Created wsx.d.ts at: ${wsxTypesLocation}\n   Full path: ${wsxTypesPath}\n   This file enables TypeScript support for .wsx files.\n`
            );
        }

        // Try to update tsconfig.json
        const tsconfigUpdated = updateTsConfig(projectRoot, wsxTypesLocation);
        if (tsconfigUpdated) {
            console.log(
                `[@wsxjs/wsx-core] ✅ Updated tsconfig.json to include ${wsxTypesLocation}\n`
            );
        }
    } catch (error) {
        // Don't fail the install if postinstall script has issues
        console.warn("[@wsxjs/wsx-core] Postinstall script warning:", error.message);
    }
}

main();
